const mongoose = require("mongoose")
const { Schema, model } = mongoose;


//no need for time since the object ID for the post will contain it
const PostSchema = Schema({
    title: { type: String, required: true },
    summary: { type: String, required: true },
    imageURL: { type: String, required: true },
    text: { type: String, required: true },
    author: { type: String, required: true },
    authorID: { type: String, required: true }  //corresponds to UserID auto generated by db

})

const PostModel = model("Post", PostSchema);

module.exports = PostModel;